# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: iot.io
author:
  name: Duncan Wilson
  email: hello@iot.io

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Pages on the internet of a London based engineer, interested in the 
  intersection between design, nature, cities and the internet of things. Currently 
  working at UCL Bartlett CASA in London.


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.iot.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: djdunc
github_username:  djdunc

# Build settings
# Copied across the minima theme _includes _layouts _ sass and assets folders
# So now using regular theme rather than gem
#theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y" 

  # Generate social links in footer.
  #
 social_links:
   - { platform: github,         user_url: "https://github.com/djdunc" }
   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/duncanwilson" }
   - { platform: mastodon,       user_url: "https://mastodon.me.uk/@dunc" }
   - { platform: flickr,         user_url: "https://www.flickr.com/photos/pseudonomad" }
   - { platform: pinboard,      user_url: "http://pinboard.in/u:dunc" }
   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=CKqcXwEAAAAJ&hl=en" }
   - { platform: twitter,        user_url: "https://twitter.com/djdunc" }
   - { platform: youtube,        user_url: "https://vimeo.com/djdunc" }
   - { platform: lastfm,         user_url: "http://www.last.fm/user/djdunc" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - hello.md
  - blog.md
  - projects.md

# Set to `true` to show excerpts on the homepage.
#
show_excerpts: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - old/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
